server:
  port: 9501

spring:
  application:
    name: gateway-proxy
  cloud:
    gateway:
      routes:
      - id: url-proxy-1
        uri: https://www.baidu.com
        predicates:
        - Path=/baidu/**
        filters:
          - StripPrefix=1
      - id: user-server
        uri: http://localhost:9301/
        predicates:
        - Path=/userService/**
        filters:
          - StripPrefix=1
      - id: user-server2
        uri: lb://user-server
        predicates:
        - Path=/userService2/**
        filters:
          - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/