server:
  port: 8090

spring:
  application:
    name: springboot-rabbit
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ems
    password: ems
    virtual-host: /ems
    # 消息发送到交换机确认机制 是否需要回调
    publisher-returns: true
    publisher-confirm-type: simple
    listener:
      direct:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5
      #        prefetch: 1
      type: simple
      simple:
        concurrency: 5
        max-concurrency: 10
        # 消息开启手动确认
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 5